### ISSUE TITLE
scrape_posts runs forever

### ISSUE THREAD

**Issue by arnemoor** [Amenly/OnlyFans-AutoLiker#1]
In scrape_posts the following is hanging, the spinner is going and going, if I add a timeout I see a status code 200 but no results. 
with requests.Session() as s:
            r = s.get(url.format(
                self.id, self.posts_count, slot, self.app_token),
                headers=self.headers)
Any idea how to dive deeper or fix?

**Comment by Amenly** [comment]
It never finished? It might take awhile to gather all of a user's posts if they have thousands of them, but this is only due to the way OnlyFans has it set up.

Could you tell me which profile you tried it on?

**Comment by Amenly** [comment]
It was a little difficult to diagnose this issue but I believe I figured out what it was. If you ran the program on a content creator who has pay-per-view timeline posts with visible images/videos (essentially preview media), the program would run forever. Hopefully this latest version fixes any issues you had.
