### ISSUE TITLE
ERROR: Unable to like post -- Received 401 STATUS CODE

### ISSUE THREAD

**Issue by NotoriousFan** [Amenly/OnlyFans-AutoLiker#3]
After inputting everything, I get this looping message "ERROR: Unable to like post -- Received 401 STATUS CODE"

**Comment by Amenly** [comment]
Apart from the `app_token`, which of these fields do you currently have filled out:

```json
{
    "auth": {
        "auth_id": "",
        "auth_uid_": "",
        "sess": "",
        "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
        "user_agent": ""
    }
}
```

When I had that issue, it was because I updated my browser and I forgot to update the `user_agent`.

**Comment by NotoriousFan** [comment]
I tried it today by copying again the information from my Digital criminal's script and everything works fine now. 
I probably copied user_agent  wrong the first time haha. Thank you
