### ISSUE TITLE
video tutorial

### ISSUE THREAD

**Issue by Anarhcy** [Amenly/OnlyFans-AutoLiker#4]
Hi man! thanks alot for your job!
 Could you make a video guide or tutorial how to work with that script? 
Really need that tool right now, but iam to stupid in that.

**Comment by Amenly** [comment]
Unfortunately, I can't do a video tutorial but the set up here is the same as the set up for [DIGITALCRIMINAL's script](https://github.com/DIGITALCRIMINAL/OnlyFans). If you know how to use his script, using this one should be just as easy.
