### ISSUE TITLE
Unable to find auth, sess etc.

### ISSUE THREAD

**Issue by AlexBaldry** [Amenly/OnlyFans-AutoLiker#5]
I got CTRL SHIFT I and refresh the page. Nothing anywhere.

**Comment by AlexBaldry** [comment]
![image](https://user-images.githubusercontent.com/48566683/113767587-c67baa00-9716-11eb-9403-7304af05ece6.png)

**Comment by Amenly** [comment]
If you click on the first one (the `init` one), a sidebar will open. Then, in that sidebar, scroll down until you see a section called `Request Headers` and your cookies will be in the `Cookie` section.
